[package]
name = "pigeon"
version = "0.0.0"
authors = ["UAV Austin <uavaustin@gmail.com>"]
license = "MIT"

[badges]
travis-ci = { repository = "uavaustin/pigeon", branch = "master" }

[dependencies]
